# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
      
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.13.2

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          host: windows
          arch: win64_msvc2022_64
          target: 'desktop'
          version: '6.8.2'

      - name: Get ffmpeg binaries
        run: |
          Invoke-WebRequest -Uri "https://github.com/GyanD/codexffmpeg/releases/download/8.1.1/ffmpeg-8.1.1-full_build-shared.zip" -OutFile "ffmpeg.zip"
          Expand-Archive ffmpeg.zip -DestinationPath "ffmpeg-build"
          New-Item -ItemType Directory -Force -Path "C:\ffmpeg"
          Move-Item -Path "ffmpeg-build\*\*" -Destination "C:\ffmpeg"

      - name: Compile Windows native target
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DAVFORMAT_INCLUDE_DIRS="C:/ffmpeg/include" -DAVFORMAT_LIBRARIES="C:/ffmpeg/lib/avformat.lib" ^
            -DAVCODEC_INCLUDE_DIRS="C:/ffmpeg/include" -DAVCODEC_LIBRARIES="C:/ffmpeg/lib/avcodec.lib" ^
            -DAVUTIL_INCLUDE_DIRS="C:/ffmpeg/include" -DAVUTIL_LIBRARIES="C:/ffmpeg/lib/avutil.lib" ^
            -DSWRESAMPLE_INCLUDE_DIRS="C:/ffmpeg/include" -DSWRESAMPLE_LIBRARIES="C:/ffmpeg/lib/swresample.lib"
          cmake --build build --config Release

      - name: Package Windows artifacts
        shell: cmd
        run: |
          set PATH=%Qt6_DIR%\bin;%PATH%
          windeployqt --qmldir src build/main.exe
          copy "C:\ffmpeg\bin\*.dll" "build\"

      - name: Test executable
        shell: powershell
        run: |
          $process = Start-Process -FilePath "build\main.exe" -PassThru
          Start-Sleep -Seconds 5

          if ($process.HasExited) {
            Write-Error "Program crashed!"
            exit 1
          } else {
            Write-Output "Program started successfully! Closing..."
            Stop-Process -Id $process.Id
          }

      - name: Upload Windows result
        uses: actions/upload-artifact@v4
        with:
          name: Speedshifter-Windows-x64
          path: build/
        
        
