# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.13.2

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          host: windows
          arch: win64_msvc2022_64
          target: "desktop"
          version: "6.8.2"

      - name: Set up MSVC developer environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Get ffmpeg binaries
        run: |
          Invoke-WebRequest -Uri "https://github.com/GyanD/codexffmpeg/releases/download/8.1.1/ffmpeg-8.1.1-full_build-shared.zip" -OutFile "ffmpeg.zip"
          Expand-Archive ffmpeg.zip -DestinationPath "ffmpeg-build"
          New-Item -ItemType Directory -Force -Path "C:\ffmpeg"
          Move-Item -Path "ffmpeg-build\*\*" -Destination "C:\ffmpeg"

      - name: Compile Windows native target
        shell: cmd
        run: |
          cmake -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DAVFORMAT_INCLUDE_DIRS="C:/ffmpeg/include" -DAVFORMAT_LIBRARIES="C:/ffmpeg/lib/avformat.lib" ^
            -DAVCODEC_INCLUDE_DIRS="C:/ffmpeg/include" -DAVCODEC_LIBRARIES="C:/ffmpeg/lib/avcodec.lib" ^
            -DAVUTIL_INCLUDE_DIRS="C:/ffmpeg/include" -DAVUTIL_LIBRARIES="C:/ffmpeg/lib/avutil.lib" ^
            -DSWRESAMPLE_INCLUDE_DIRS="C:/ffmpeg/include" -DSWRESAMPLE_LIBRARIES="C:/ffmpeg/lib/swresample.lib"
          cmake --build build --config Release

      - name: Package Windows artifacts
        shell: cmd
        run: |
          set PATH=%Qt6_DIR%\bin;%PATH%
          windeployqt --qmldir src\qml build/main.exe
          copy "C:\ffmpeg\bin\*.dll" "build\"

      - name: Smoke test packaged executable
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "build"
          $stdout = "build\main.stdout.log"
          $stderr = "build\main.stderr.log"

          # add qt and ffmpeg to PATH
          $env:PATH = "{{ env.Qt6_DIR }}\bin;C:\ffmpeg\bin;" + $env:PATH

          try {
            Write-Host "Starting test..."
            $process = Start-Process -FilePath "build\main.exe" -ArgumentList "-platform", "offscreen" -PassThru `
                -RedirectStandardOutput $stdout -RedirectStandardError $stderr
            $process.WaitForExit(10000)

            if (!$process.HasExited) {
              Write-Host "Process timed out. Killing it..."
              Stop-Process -Id $process.Id -Force
            }
          }
          catch {
            Write-Host "::error::Failed to test program: $_"
          }
          finally {
            Write-Host "::group::main.exe stdout"
            if (Test-Path $stdout) { Get-Content $stdout } else { Write-Host "No stdout log found." }
            Write-Host "::endgroup::"

            Write-Host "::group::main.exe stderr"
            if (Test-Path $stderr) { Get-Content $stderr } else { Write-Host "No stderr log found." }
            Write-Host "::endgroup::"

            if ($null -eq $process) {
              exit 1
            } elseif ($process.ExitCode -ne 0) {
              Write-Host "::error::Packaged executable exited with code $($process.ExitCode)"
              exit $process.ExitCode
            }
          }

      - name: Upload smoke test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-logs
          path: build/*.log

      - name: Upload Windows result
        if: always() # so we can test executable on our own
        uses: actions/upload-artifact@v4
        with:
          name: Speedshifter-Windows-x64
          path: build/
